USE OnlineShop;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT Goods_ID, price FROM Goods WHERE Goods_ID = 'G002';
PRINT '以上是 READ UNCOMMITTED 的結果';

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT Goods_ID, price FROM Goods WHERE Goods_ID = 'G002';
PRINT '以上是 READ COMMITTED 的結果';